name: CI/CD Alpha Env

on:
  pull_request:
    types: [closed]
    branches:
      - alpha*

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
    
      #======CONFIGURACOES DO ACTIONS======#
      #Fazendo o clone da branch
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
      

      - name: Increment Version
        if: ${{ github.event.pull_request.merged == true}}
        run: |
          echo ${{ github }} 
          echo ${{ github.REF }}
          echo ${{ github.event.after }}
          
      - name: Increment Version
        run: |
          ./version_manager.py sc alpha fix
