name: CI/CD Alpha Env

on:
  pull_request:
    types: [closed]
    branches:
      - alpha*

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
    
      #======CONFIGURACOES DO ACTIONS======#
      #Fazendo o clone da branch
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
      
      - name: Increment Version      
        if: ${{ github.event.pull_request.merged == true}}
        run: |
          cd .scripts
          ./version_manager.py ${{ github.BASE_REF }} ${{ github.HEAD_REF }}
